export const ActionTypes = {

  PARTICIPANT_FORM_UPDATE: "PARTICIPANT_FORM_UPDATE",

  PARTICIPANTS_FETCHING: "PARTICIPANTS_FETCHING",
  PARTICIPANTS_FETCH_SUCCESS: "PARTICIPANTS_FETCH_SUCCESS",

  PARTICIPANT_SAVING: "PARTICIPANT_SAVING",
  PARTICIPANT_SAVE_SUCCESS: "PARTICIPANT_SAVE_SUCCESS",
  PARTICIPANT_SAVE_FAIL: "PARTICIPANT_SAVE_FAIL",
  PARTICIPANT_SAVE_VALIDATION_ERROR: "PARTICIPANT_SAVE_VALIDATION_ERROR",

  PARTICIPANTS_SORT: "PARTICIPANTS_SORT",

  PARTICIPANT_DELETING: "PARTICIPANT_DELETING",
  PARTICIPANT_DELETE_SUCCESS: "PARTICIPANT_DELETE_SUCCESS",
  PARTICIPANT_DELETE_FAIL: "PARTICIPANT_DELETE_FAIL",
}