export const ActionTypes = {

  PARTICIPANTS_FETCHING: "PARTICIPANTS_FETCHING",
  PARTICIPANTS_FETCH_SUCCESS: "PARTICIPANTS_FETCH_SUCCESS",

  PARTICIPANT_SAVING: "PARTICIPANT_SAVING",
  PARTICIPANT_SAVE_SUCCESS: "PARTICIPANT_SAVE_SUCCESS",
  PARTICIPANT_SAVE_FAIL: "PARTICIPANT_SAVE_FAIL",
  PARTICIPANT_SAVE_VALIDATION_ERROR: "PARTICIPANT_SAVE_VALIDATION_ERROR",

}