export const ActionTypes = {

  PARTICIPANTS_GENERATING: "PARTICIPANTS_GENERATING",
  PARTICIPANTS_GENERATE_SUCCESS: "PARTICIPANTS_GENERATE_SUCCESS",
  PARTICIPANTS_GENERATE_ERROR: "PARTICIPANTS_GENERATE_ERROR",

  PARTICIPANT_SAVING: "PARTICIPANT_SAVING",
  PARTICIPANT_SAVE_SUCCESS: "PARTICIPANT_SAVE_SUCCESS",
  PARTICIPANT_SAVE_FAIL: "PARTICIPANT_SAVE_FAIL",
  PARTICIPANT_SAVE_VALIDATION_ERROR: "PARTICIPANT_SAVE_VALIDATION_ERROR",

}